// <auto-generated />
using System;
using FilmDB.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FilmDB.DAL.Migrations
{
    [DbContext(typeof(FilmDBContext))]
    partial class FilmDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FilmDB.DAL.Models.Gesehen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Bewertung")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GesehenAm")
                        .HasColumnType("date");

                    b.Property<int>("GesehenBeiID")
                        .HasColumnType("integer");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.HasIndex("GesehenBeiID");

                    b.ToTable("Gesehen");
                });

            modelBuilder.Entity("FilmDB.DAL.Models.Sender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Sendername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("Sender");
                });

            modelBuilder.Entity("FilmDB.DAL.Models.Gesehen", b =>
                {
                    b.HasOne("FilmDB.DAL.Models.Sender", "GesehenBei")
                        .WithMany()
                        .HasForeignKey("GesehenBeiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GesehenBei");
                });
#pragma warning restore 612, 618
        }
    }
}
